/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'date' : string,
  'guestCount' : bigint,
  'time' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'category' : string,
  'price' : number,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'totalAmount' : number,
  'timestamp' : bigint,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'itemId' : bigint,
  'itemName' : string,
  'quantity' : bigint,
  'price' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [string, string, string, string, bigint],
    bigint
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string, Array<OrderItem>], bigint>,
  'removeMenuItem' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedMenu' : ActorMethod<[], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, string], undefined>,
  'updateMenuItem' : ActorMethod<[bigint, MenuItem], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];